//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terra.NET.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JsonExamples {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JsonExamples() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Terra.NET.Tests.JsonExamples", typeof(JsonExamples).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///              &quot;type&quot;: &quot;wasm/MsgExecuteContract&quot;,
        ///              &quot;value&quot;: {
        ///                &quot;coins&quot;: [
        ///                  {
        ///                    &quot;denom&quot;: &quot;uusd&quot;,
        ///                    &quot;amount&quot;: &quot;759502835&quot;
        ///                  }
        ///                ],
        ///                &quot;sender&quot;: &quot;terra12hjzrwvntaxndt2fwl3j0qyw7vqjr96d0j5qpr&quot;,
        ///                &quot;contract&quot;: &quot;terra1fxwelge6mf5l6z0rjpylzcfq9w9tw2q7tewaf5&quot;,
        ///                &quot;execute_msg&quot;: {
        ///                  &quot;bond&quot;: {
        ///                    &quot;assets&quot;: [
        ///               [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExecuteContractMessage {
            get {
                return ResourceManager.GetString("ExecuteContractMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///      &quot;id&quot;: 171051354,
        ///      &quot;chainId&quot;: &quot;columbus-5&quot;,
        ///      &quot;tx&quot;: {
        ///        &quot;type&quot;: &quot;core/StdTx&quot;,
        ///        &quot;value&quot;: {
        ///          &quot;fee&quot;: {
        ///            &quot;gas&quot;: &quot;2157800&quot;,
        ///            &quot;amount&quot;: [
        ///              {
        ///                &quot;denom&quot;: &quot;uusd&quot;,
        ///                &quot;amount&quot;: &quot;1739579&quot;
        ///              }
        ///            ]
        ///          },
        ///          &quot;msg&quot;: [
        ///            {
        ///              &quot;type&quot;: &quot;wasm/MsgExecuteContract&quot;,
        ///              &quot;value&quot;: {
        ///                &quot;coins&quot;: [],
        ///                &quot;sender&quot;: &quot;terra12hj [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransactionBlock {
            get {
                return ResourceManager.GetString("TransactionBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///            &quot;gas&quot;: &quot;198435&quot;,
        ///            &quot;amount&quot;: [
        ///              {
        ///                &quot;denom&quot;: &quot;uusd&quot;,
        ///                &quot;amount&quot;: &quot;29766&quot;
        ///              }
        ///            ]
        ///          }.
        /// </summary>
        internal static string TransactionFee {
            get {
                return ResourceManager.GetString("TransactionFee", resourceCulture);
            }
        }
    }
}
